Cache OpenSSL build for Invidious

diff --git a/.github/workflows/invidious.yml b/.github/workflows/invidious.yml
--- a/.github/workflows/invidious.yml
+++ b/.github/workflows/invidious.yml
@@ -18,18 +18,46 @@ env:
 jobs:
   prep:
     outputs:
-      upstream-rev: ${{ steps.latest.outputs.upstream-rev }}
-      build-timestamp: ${{ steps.latest.outputs.build-timestamp }}
+      branch: ${{ steps.init.outputs.branch }}
+      expires: ${{ steps.init.outputs.expires }}
+      upstream-rev: ${{ steps.init.outputs.upstream-rev }}
+      build-timestamp: ${{ steps.init.outputs.build-timestamp }}
+      skip-release: ${{ steps.check.outputs.skip-release }}
     name: Preparation
     runs-on: ubuntu-latest
 
     steps:
-      - name: Get the latest commit
-        id: latest
+      - name: Gather current build info
+        id: init
         run: |
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+            echo "branch=${{ env.REPO_NAME }}" >> "$GITHUB_OUTPUT"
+            echo "expires=5w" >> "$GITHUB_OUTPUT"
+          else
+            echo "branch=test-${{ env.REPO_NAME }}" >> "$GITHUB_OUTPUT"
+            echo "expires=3d" >> "$GITHUB_OUTPUT"
+          fi
           rev=$(git ls-remote -h "${{ env.REPO_URL }}" "${{ env.REPO_BRANCH }}" | cut -f 1)
           echo "upstream-rev=$rev" >> "$GITHUB_OUTPUT"
           echo "build-timestamp=$(TZ=Pacific/Auckland date +%Y%m%d)" >> "$GITHUB_OUTPUT"
+      - name: Restore last build info
+        if: github.ref_name == 'main' && github.event_name == 'schedule'
+        uses: actions/cache@v6
+        with:
+          path: /tmp/GAC/${{ env.REPO_NAME }}
+          key: ${{ env.REPO_NAME }}-build
+      - name: Check last build info
+        id: check
+        run: |
+          tag_file=/tmp/GAC/${{ env.REPO_NAME }}/tag
+          last_tag=$(cat "$tag_file" 2>/dev/null || echo -n)
+          upstream_rev=${{ steps.init.outputs.upstream-rev }}
+          if [[ "$last_tag" != "$upstream_rev" ]]; then
+            mkdir -p "${tag_file%/*}"
+            echo "$upstream_rev" > "$tag_file"
+          else
+            echo 'skip-release=true' >> "$GITHUB_OUTPUT"
+          fi
 
   build:
     # amd/arm build inspired by https://github.com/iv-org/invidious/blob/master/.github/workflows/ci.yml
@@ -45,97 +73,124 @@ jobs:
           - os: ubuntu-24.04-arm
             name: ARM64
             prefix: arm64
-            platform: linux/arm64/v8
+            platform: linux/arm64
             dockerfile: docker/Dockerfile
             latest: latest-arm64
+
+    outputs:
+      openssl-version: ${{ steps.docker.outputs.openssl-version }}
     name: Build for ${{ matrix.name }}
     needs: prep
     env:
+      BRANCH: ${{ needs.prep.outputs.branch }}
       UPSTREAM_REV: ${{ needs.prep.outputs.upstream-rev }}
+      BUILD_TIMESTAMP: ${{ needs.prep.outputs.build-timestamp }}
     runs-on: ${{ matrix.os }}
 
+    if: needs.prep.outputs.skip-release != 'true'
     steps:
-      - name: Restore last build info
-        if: github.ref_name == 'main' && github.event_name == 'schedule'
-        uses: actions/cache@v3
-        with:
-          path: /tmp/GAC/${{ env.REPO_NAME }}
-          key: ${{ runner.os }}--${{ env.REPO_NAME }}
-      - name: Check last build info
-        id: check
-        run: |
-          tag_file=/tmp/GAC/${{ env.REPO_NAME }}/tag
-          last_tag=$(cat "$tag_file" 2>/dev/null || echo -n)
-          if [[ "$last_tag" != "$UPSTREAM_REV" ]]; then
-            mkdir -p "${tag_file%/*}"
-            echo "$UPSTREAM_REV" > "$tag_file"
-          else
-            echo 'skip-release=true' >> "$GITHUB_OUTPUT"
-          fi
-      - name: Set branch
-        if: steps.check.outputs.skip-release != 'true'
-        run: |
-          if [[ "${{ github.ref_name }}" == "main" ]]; then
-            echo "branch=${{ env.REPO_NAME }}" >> $GITHUB_ENV
-            echo "expires=5w" >> $GITHUB_ENV
-          else
-            echo "branch=test-${{ env.REPO_NAME }}" >> $GITHUB_ENV
-            echo "expires=3d" >> $GITHUB_ENV
-          fi
       - name: Checkout
-        uses: actions/checkout@v3
-        if: steps.check.outputs.skip-release != 'true'
+        uses: actions/checkout@v7
       - name: Download source code
-        if: steps.check.outputs.skip-release != 'true'
         run: |
           git config --global advice.detachedHead false
           git config --global user.email nobody@localhost
           git config --global user.name nobody
           echo "::group::Clone repo"
-          git clone --revision="$UPSTREAM_REV" "${{ env.REPO_URL }}" "${{ env.REPO_SRCDIR }}"
+          git clone --depth=1 --revision="$UPSTREAM_REV" "${{ env.REPO_URL }}" "${{ env.REPO_SRCDIR }}"
           cd "${{ env.REPO_SRCDIR }}"
-          git config --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
-          git fetch --all
           echo "::endgroup::"
-          echo "::group::Tag version"
-          tag=$(git rev-parse HEAD)
-          echo "$tag"
-          mkdir -p /tmp/GAC/${{ env.REPO_NAME }} && echo "$tag" > /tmp/GAC/${{ env.REPO_NAME }}/version
+          rev=$(git rev-parse HEAD)
+          echo "::group::Git info"
+          echo "Rev: $rev"
+          echo "Logs:"
+          git log -3 --oneline
           echo "::endgroup::"
-      - name: Merge patches
-        if: steps.check.outputs.skip-release != 'true'
+          if [[ "$rev" != "$UPSTREAM_REV" ]]; then
+            echo "::error::Unexpected mismatching revision"
+            echo "::error::- $rev got"
+            echo "::error::- $UPSTREAM_REV expected"
+            exit 1
+          fi
+      - name: Split Dockerfile
+        id: docker
         run: |
           cd "${{ env.REPO_SRCDIR }}"
-          for i in $(grep -vE '^#' ../${{ env.REPO_NAME }}/pr.list); do
-            echo "::group::PR#$i"
-            git merge --no-edit "origin/pr/$i"
-            echo "::endgroup::"
-          done
-          for i in $(grep -vE '^#' ../${{ env.REPO_NAME }}/xt.list); do
-            echo "::group::$i"
-            git am -3 "../${{ env.REPO_NAME }}/patches/$i"
-            echo "::endgroup::"
-          done
+          openssl_version=$(cat docker/Dockerfile | grep 'ARG OPENSSL_VERSION=' | sed -Ee "s/^.* OPENSSL_VERSION='(.*)'.*$/\\1/")
+          echo "openssl-version=$openssl_version" >> $GITHUB_OUTPUT
+          cat docker/Dockerfile | sed \
+            -e '/^FROM dependabot-crystal AS openssl-builder$/,$d' \
+            > docker/Dockerfile.invidious
+          cat docker/Dockerfile | sed \
+            -e "1i FROM quay.io/putara/${{ env.BRANCH }}-openssl:${openssl_version}-${{ matrix.prefix }}-${UPSTREAM_REV} AS openssl-builder" \
+            -e '/^FROM dependabot-crystal AS builder$/,$!d' \
+            >> docker/Dockerfile.invidious
+          cat docker/Dockerfile | sed \
+            -e '/^FROM dependabot-crystal AS builder$/,$d' \
+            -e 's/\.\/Configure /\.\/Configure no-tests /' \
+            > docker/Dockerfile.openssl
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-        if: steps.check.outputs.skip-release != 'true'
+        uses: docker/setup-buildx-action@v4
       - name: Login to Quay.io
-        uses: docker/login-action@v2
-        if: steps.check.outputs.skip-release != 'true'
+        uses: docker/login-action@v4
         with:
           registry: quay.io
           username: ${{ secrets.QUAY_USERNAME }}
           password: ${{ secrets.QUAY_PASSWORD }}
-      - name: Build and push ${{ matrix.name }}
-        uses: docker/build-push-action@v4
-        if: steps.check.outputs.skip-release != 'true'
+      - name: Build and push OpenSSL for ${{ matrix.name }}
+        uses: docker/build-push-action@v7
         with:
           context: ./${{ env.REPO_SRCDIR }}
-          file: ./${{ env.REPO_SRCDIR }}/${{ matrix.dockerfile }}
+          file: ./${{ env.REPO_SRCDIR }}/${{ matrix.dockerfile }}.openssl
           platforms: ${{ matrix.platform }}
           labels: quay.expires-after=${{ env.expires }}
           push: true
-          tags: quay.io/putara/${{ env.branch }}:${{ matrix.latest }}, quay.io/putara/${{ env.branch }}:${{ matrix.prefix }}-${{ needs.prep.outputs.build-timestamp }}
+          tags: quay.io/putara/${{ env.BRANCH }}-openssl:${{ steps.docker.outputs.openssl-version }}-${{ matrix.prefix }}-${{ env.UPSTREAM_REV }}
+      - name: Build and push Invidious for ${{ matrix.name }}
+        uses: docker/build-push-action@v7
+        with:
+          context: ./${{ env.REPO_SRCDIR }}
+          file: ./${{ env.REPO_SRCDIR }}/${{ matrix.dockerfile }}.invidious
+          platforms: ${{ matrix.platform }}
+          labels: quay.expires-after=${{ env.expires }}
+          push: true
+          tags: quay.io/putara/${{ env.BRANCH }}:${{ matrix.latest }}, quay.io/putara/${{ env.BRANCH }}:${{ matrix.prefix }}-${{ env.BUILD_TIMESTAMP }}
           build-args: |
             "release=1"
             "disable_quic=1"
+
+  merge:
+    name: Merge
+    needs:
+      - prep
+      - build
+    env:
+      BRANCH: ${{ needs.prep.outputs.branch }}
+      UPSTREAM_REV: ${{ needs.prep.outputs.upstream-rev }}
+      OPENSSL_VERSION: ${{ needs.build.outputs.openssl-version }}
+    runs-on: ubuntu-latest
+
+    if: needs.prep.outputs.skip-release != 'true'
+    steps:
+      - name: Login to Quay.io
+        uses: docker/login-action@v4
+        with:
+          registry: quay.io
+          username: ${{ secrets.QUAY_USERNAME }}
+          password: ${{ secrets.QUAY_PASSWORD }}
+      - name: Create and push OpenSSL
+        uses: int128/docker-manifest-create-action@v2
+        with:
+          push: true
+          tags: quay.io/putara/${{ env.BRANCH }}-openssl:${{ env.OPENSSL_VERSION }}-${{ env.UPSTREAM_REV }}
+          sources: |
+            quay.io/putara/${{ env.BRANCH }}-openssl:${{ env.OPENSSL_VERSION }}-amd64-${{ env.UPSTREAM_REV }}
+            quay.io/putara/${{ env.BRANCH }}-openssl:${{ env.OPENSSL_VERSION }}-arm64-${{ env.UPSTREAM_REV }}
+      - name: Create and push Invidious
+        uses: int128/docker-manifest-create-action@v2
+        with:
+          push: true
+          tags: quay.io/putara/${{ env.BRANCH }}:latest
+          sources: |
+             quay.io/putara/${{ env.BRANCH }}:latest
+             quay.io/putara/${{ env.BRANCH }}:latest-arm64
